#if os(macOS)
import Foundation
import OpsNotchCore

@MainActor
enum L10n {
    static func text(_ key: String, _ language: AppLanguage) -> String {
        let zh: [String: String] = [
            "quickShelf": "快速暂存",
            "shelfInspector": "条目详情",
            "shelfSourceDesktop": "桌面",
            "shelfSourceFinder": "Finder / 本地路径",
            "shelfPreviewUnavailable": "暂无预览",
            "shelfSectionContext": "上下文",
            "shelfSectionNow": "当前工作",
            "shelfSectionFavorites": "收藏",
            "shelfSectionRecent": "最近",
            "shelfSectionResults": "结果",
            "shelfClearSearch": "清除搜索",
            "shelfTimeNow": "刚刚",
            "shelfTimeMinutes": "%d 分钟前",
            "shelfTimeHours": "%d 小时前",
            "shelfTimeDays": "%d 天前",
            "shelfKindImage": "图片",
            "shelfKind_text": "文本",
            "shelfKind_url": "URL",
            "shelfKind_file": "文件",
            "shelfKind_folder": "文件夹",
            "shelfKind_application": "应用",
            "shelfKind_action": "操作",
            "shelfAdditionalActions": "更多操作",
            "presentationShowDesktops": "显示桌面",
            "presentationSwitchDesktop": "切换桌面",
            "presentationOpen": "打开",
            "presentationClipboardImage": "剪贴板图片",
            "presentationLocalPath": "本地路径",
            "presentationSafeAction": "安全操作",
            "presentationFloatingPreview": "放大预览",
            "pinned": "收藏",
            "recent": "智能最近",
            "workingSet": "工作集",
            "workingSetAdd": "加入工作集",
            "workingSetRemove": "移出工作集",
            "workingSetAdded": "已加入工作集",
            "workingSetRemoved": "已移出工作集",
            "workingSetCleared": "工作集已清空",
            "search": "搜索名称或内容…",
            "searchUnified": "搜索或输入命令…",
            "searchCommandHelp": "d2 切换桌面 · ~/Downloads 打开路径 · type:file report 筛选 · @fav 收藏",
            "finderQuickPaths": "Finder 快捷目录",
            "finderDefaultPath": "默认目录",
            "openFolder": "打开目录",
            "copyPath": "复制路径",
            "pathCopied": "路径已复制",
            "unifiedFooter": "Finder + 工作集 + Smart Recent",
            "semanticIP": "IP",
            "semanticSSH": "SSH",
            "semanticCommand": "命令",
            "semanticPath": "路径",
            "semanticURL": "URL",
            "add": "添加",
            "settings": "设置",
            "clear": "清空",
            "copied": "已复制",
            "clipboardCaught": "已暂存刚复制的文字",
            "empty": "这里还没有内容",
            "emptyHint": "拖文件或文字到刘海，或复制文字后触碰刘海。",
            "addText": "新建文字",
            "addFile": "添加文件…",
            "addFolder": "添加文件夹…",
            "addURL": "添加网址…",
            "addApp": "添加应用…",
            "addAction": "添加安全操作…",
            "copy": "复制",
            "quickLook": "快速预览",
            "reveal": "在 Finder 中显示",
            "pin": "置顶",
            "unpin": "取消置顶",
            "edit": "编辑",
            "remove": "移除",
            "deleteSelected": "删除所选",
            "copySelected": "复制所选",
            "selected": "已选择",
            "dropTitle": "松开即可放入",
            "dropHint": "文件、文件夹、网址和文字均可直接拖入",
            "dropReference": "引用原文件",
            "dropCopy": "复制到暂存区",
            "name": "名称",
            "content": "内容",
            "cancel": "取消",
            "save": "保存",
            "general": "通用",
            "language": "语言",
            "launchAtLogin": "登录时启动",
            "displayTarget": "显示位置",
            "keepShelfOpen": "常驻展开",
            "keepShelfOpenOn": "常驻展开（不自动隐藏）",
            "keepShelfOpenOff": "取消常驻",
            "allDisplays": "所有显示器",
            "mouseDisplay": "鼠标所在屏幕",
            "primaryDisplay": "主屏幕",
            "currentDisplay": "最近使用屏幕",
            "storage": "暂存",
            "fileDropMode": "文件放置方式",
            "reference": "引用原文件",
            "copyIn": "复制进来",
            "recentCleanup": "Recent 自动清理",
            "never": "永不",
            "oneHour": "1 小时",
            "oneDay": "24 小时",
            "threeDays": "3 天",
            "sevenDays": "7 天",
            "clipboardHint": "Enter 使用 · ⌘P 收藏 · ⌘D 删除 · Space 预览",
            "shortcutUse": "Enter 使用",
            "shortcutPin": "⌘P 收藏",
            "shortcutDelete": "⌘D 删除",
            "shortcutPreview": "Space 预览",
            "openShelf": "打开快速暂存区",
            "newText": "新建文字…",
            "quit": "退出 Ops Notch",
            "safePath": "本地路径",
            "safeURL": "HTTP/HTTPS URL",
            "invalidAction": "安全操作只允许本地绝对路径或 HTTP/HTTPS URL。",
            "invalidPathInput": "本地路径须以 / 或 ~ 开头。",
            "invalidURLInput": "仅支持 HTTP/HTTPS 网址。",
            "dragHandle": "拖动",
            "zoomPreview": "放大预览",
            "previewClose": "关闭",
            "previewFont": "字号",
            "previewFit": "适配窗口",
            "previewZoomIn": "放大",
            "previewZoomOut": "缩小",
            "appTitle": "Ops Notch",
            "settingsTitle": "Ops Notch 设置",
            "hotkeyRow": "呼出快捷键",
            "hotkeyNone": "未设置(点击录制)",
            "hotkeyRecording": "按下组合键,Esc 取消",
            "hotkeyRerecordHint": "点击重新录制,⌫ 清除",
            "hotkeyInvalid": "组合需包含 ⌘/⌃/⌥ 之一",
            "hotkeyConflict": "该组合键已被占用,请换一组",
            "hotkeyHint": "在任意应用中按下快捷键即可呼出 Smart Quick Shelf；Finder、工作集和剪贴板内容在同一面板。",
            "filterAll": "全部",
            "filterFile": "文件",
            "filterText": "文本",
            "filterURL": "URL",
            "filterApp": "应用",
            "filterAction": "安全操作",
            "noMatch": "没有匹配的条目",
            "desktop": "桌面",
            "desktopList": "快速切换桌面",
            "desktopCurrent": "当前",
            "desktopFullscreen": "全屏",
            "desktopNoSpaces": "没有可切换的桌面",
            "desktopAccessibilityRequired": "请授予 Ops Notch 辅助功能权限，然后激活原窗口并重新呼出工具",
            "desktopTopologyUnavailable": "无法读取 macOS 桌面信息",
            "desktopNotFound": "未找到桌面 %d",
            "desktopSwitchFailed": "切换到桌面 %d 失败",
            "desktopMoveWindow": "将当前窗口移到桌面 %d",
            "desktopMoveAndFollow": "移动当前窗口并跟随到桌面 %d",
            "desktopMoveHint": "⌥ + 选择桌面行：移动 · ⌥⇧ + 选择桌面行：移动并跟随",
            "desktopDisplay": "显示器",
            "desktopMoveSource": "操作窗口来自：%@",
            "desktopMoveMenu": "移动当前窗口到…",
            "desktopFollowMenu": "移动当前窗口并跟随到…",
            "desktopActionBusy": "正在处理桌面操作，请稍候",
            "desktopSingleSpaceRequired": "请选择只属于一个普通桌面的窗口；检查应用是否分配到所有桌面",
            "desktopSeparateSpacesRequired": "跨显示器移动需要开启“显示器具有单独的空间”，并按系统提示重新登录",
            "desktopDisplayLayoutChanged": "显示器布局已改变，操作已停止；请重新选择目标桌面",
            "desktopTargetDisplayFullscreen": "请先将目标显示器从全屏或分屏切回普通桌面，再移动窗口",
            "desktopDisplayPlacementFailed": "未确认窗口完整进入目标显示器；请检查窗口位置后重试",
            "desktopMoveFocusFailed": "窗口已移动，但未能恢复原窗口焦点；请在目标桌面点击该窗口",
            "desktopFullscreenMoveUnsupported": "暂不支持移动全屏窗口，或移入全屏、分屏桌面",
            "desktopWindowUnavailable": "未找到原来的普通窗口；请激活目标应用窗口后重新呼出工具",
            "desktopWindowIDUnavailable": "无法识别当前活动窗口",
            "desktopMoveUnavailable": "当前 macOS 版本不支持此窗口移动方式",
            "desktopMoveFailed": "未完成移动到桌面 %d；窗口可能停在目标显示器当前桌面，请检查后重试",
            "desktopMoveFollowFailed": "窗口已移到桌面 %d，但跟随切换失败",
            "seconds": "秒",
        ]
        let en: [String: String] = [
            "quickShelf": "Quick Shelf",
            "shelfInspector": "Item details",
            "shelfSourceDesktop": "Desktop",
            "shelfSourceFinder": "Finder / Local path",
            "shelfPreviewUnavailable": "Preview unavailable",
            "shelfSectionContext": "Context",
            "shelfSectionNow": "Now",
            "shelfSectionFavorites": "Favorites",
            "shelfSectionRecent": "Recent",
            "shelfSectionResults": "Results",
            "shelfClearSearch": "Clear search",
            "shelfTimeNow": "now",
            "shelfTimeMinutes": "%dm ago",
            "shelfTimeHours": "%dh ago",
            "shelfTimeDays": "%dd ago",
            "shelfKindImage": "Image",
            "shelfKind_text": "Text",
            "shelfKind_url": "URL",
            "shelfKind_file": "File",
            "shelfKind_folder": "Folder",
            "shelfKind_application": "App",
            "shelfKind_action": "Action",
            "shelfAdditionalActions": "More actions",
            "presentationShowDesktops": "Show Desktops",
            "presentationSwitchDesktop": "Switch Desktop",
            "presentationOpen": "Open",
            "presentationClipboardImage": "Clipboard image",
            "presentationLocalPath": "Local path",
            "presentationSafeAction": "Safe action",
            "presentationFloatingPreview": "Expanded Preview",
            "pinned": "Favorites",
            "recent": "Smart Recent",
            "workingSet": "Working Set",
            "workingSetAdd": "Add to Working Set",
            "workingSetRemove": "Remove from Working Set",
            "workingSetAdded": "Added to Working Set",
            "workingSetRemoved": "Removed from Working Set",
            "workingSetCleared": "Working Set cleared",
            "search": "Search name or content…",
            "searchUnified": "Search or enter a command…",
            "searchCommandHelp": "d2 desktop · ~/Downloads path · type:file report filter · @fav favorites",
            "finderQuickPaths": "Finder Quick Folders",
            "finderDefaultPath": "Default Folder",
            "openFolder": "Open Folder",
            "copyPath": "Copy Path",
            "pathCopied": "Path copied",
            "unifiedFooter": "Finder + Working Set + Smart Recent",
            "semanticIP": "IP",
            "semanticSSH": "SSH",
            "semanticCommand": "Command",
            "semanticPath": "Path",
            "semanticURL": "URL",
            "add": "Add",
            "settings": "Settings",
            "clear": "Clear",
            "copied": "Copied",
            "clipboardCaught": "Clipboard item saved",
            "clipboardImageCaught": "Clipboard image saved",
            "empty": "Nothing here yet",
            "emptyHint": "Drag files or text to the notch, or copy text and touch the notch.",
            "addText": "New Text",
            "addFile": "Add File…",
            "addFolder": "Add Folder…",
            "addURL": "Add URL…",
            "addApp": "Add Application…",
            "addAction": "Add Safe Action…",
            "copy": "Copy",
            "quickLook": "Quick Look",
            "reveal": "Show in Finder",
            "pin": "Pin",
            "unpin": "Unpin",
            "edit": "Edit",
            "remove": "Remove",
            "deleteSelected": "Delete selected",
            "copySelected": "Copy selected",
            "selected": "Selected",
            "dropTitle": "Release to add",
            "dropHint": "Files, folders, URLs and text are accepted",
            "dropReference": "Reference original",
            "dropCopy": "Copy into Shelf",
            "name": "Name",
            "content": "Content",
            "cancel": "Cancel",
            "save": "Save",
            "general": "General",
            "language": "Language",
            "launchAtLogin": "Launch at login",
            "displayTarget": "Show on",
            "keepShelfOpen": "Keep Shelf Open",
            "keepShelfOpenOn": "Keep open (no auto-hide)",
            "keepShelfOpenOff": "Turn off Keep Open",
            "allDisplays": "All displays",
            "mouseDisplay": "Display under pointer",
            "primaryDisplay": "Primary display",
            "currentDisplay": "Last used display",
            "storage": "Shelf",
            "fileDropMode": "File drop mode",
            "reference": "Reference original",
            "copyIn": "Copy in",
            "recentCleanup": "Recent cleanup",
            "never": "Never",
            "oneHour": "1 hour",
            "oneDay": "24 hours",
            "threeDays": "3 days",
            "sevenDays": "7 days",
            "clipboardHint": "Enter Use · ⌘P Favorite · ⌘D Delete · Space Preview",
            "shortcutUse": "Enter Use",
            "shortcutPin": "⌘P Favorite",
            "shortcutDelete": "⌘D Delete",
            "shortcutPreview": "Space Preview",
            "openShelf": "Open Quick Shelf",
            "newText": "New Text…",
            "quit": "Quit Ops Notch",
            "safePath": "Local path",
            "safeURL": "HTTP/HTTPS URL",
            "invalidAction": "Safe Action only supports an absolute local path or HTTP/HTTPS URL.",
            "invalidPathInput": "Local path must start with / or ~.",
            "invalidURLInput": "Only HTTP/HTTPS URLs are supported.",
            "dragHandle": "Drag",
            "zoomPreview": "Magnify",
            "previewClose": "Close",
            "previewFont": "Font size",
            "previewFit": "Fit to Window",
            "previewZoomIn": "Zoom In",
            "previewZoomOut": "Zoom Out",
            "appTitle": "Ops Notch",
            "settingsTitle": "Ops Notch Settings",
            "hotkeyRow": "Summon Hotkey",
            "hotkeyNone": "Not set (click to record)",
            "hotkeyRecording": "Press keys, Esc to cancel",
            "hotkeyRerecordHint": "Click to re-record, ⌫ to clear",
            "hotkeyInvalid": "Combination must include ⌘/⌃/⌥",
            "hotkeyConflict": "Combination already in use, try another",
            "hotkeyHint": "Press the hotkey in any app to summon Smart Quick Shelf with Finder, Working Set and clipboard content together.",
            "filterAll": "All",
            "filterFile": "Files",
            "filterText": "Text",
            "filterURL": "URLs",
            "filterApp": "Apps",
            "filterAction": "Actions",
            "noMatch": "No matching items",
            "desktop": "Desktop",
            "desktopList": "Switch Desktop",
            "desktopCurrent": "Current",
            "desktopFullscreen": "Full Screen",
            "desktopNoSpaces": "No switchable desktops found",
            "desktopAccessibilityRequired": "Grant Ops Notch Accessibility permission, activate the original window, then summon again",
            "desktopTopologyUnavailable": "Unable to read macOS desktop information",
            "desktopNotFound": "Desktop %d was not found",
            "desktopSwitchFailed": "Could not switch to Desktop %d",
            "desktopMoveWindow": "Move current window to Desktop %d",
            "desktopMoveAndFollow": "Move current window and follow to Desktop %d",
            "desktopMoveHint": "⌥ + select a desktop row: move · ⌥⇧ + select: move and follow",
            "desktopDisplay": "Display",
            "desktopMoveSource": "Window from: %@",
            "desktopMoveMenu": "Move current window to…",
            "desktopFollowMenu": "Move current window and follow to…",
            "desktopActionBusy": "A desktop action is in progress. Please wait",
            "desktopSingleSpaceRequired": "Choose a window on one normal desktop; check whether the app is assigned to All Desktops",
            "desktopSeparateSpacesRequired": "Enable Displays have separate Spaces and log in again as requested by macOS",
            "desktopDisplayLayoutChanged": "The display layout changed. Operation stopped; select the destination again",
            "desktopTargetDisplayFullscreen": "Switch the destination display out of Full Screen or Split View to a normal desktop first",
            "desktopDisplayPlacementFailed": "Could not confirm the complete window on the destination display. Check its position and retry",
            "desktopMoveFocusFailed": "The window moved, but its focus could not be restored. Click it on the destination desktop",
            "desktopFullscreenMoveUnsupported": "Moving full-screen windows or moving into Full Screen / Split View is not supported",
            "desktopWindowUnavailable": "The original normal window is unavailable. Activate the intended app window and summon again",
            "desktopWindowIDUnavailable": "Unable to identify the active window",
            "desktopMoveUnavailable": "This macOS version does not support this window move method",
            "desktopMoveFailed": "Move to Desktop %d is incomplete; the window may be on that display's current desktop. Check and retry",
            "desktopMoveFollowFailed": "The window moved to Desktop %d, but following it failed",
            "seconds": "sec",
        ]
        return (language == .zhCN ? zh : en)[key] ?? key
    }
}
#endif