#if os(macOS)
import Foundation
import OpsNotchCore

@MainActor
enum L10n {
    static func text(_ key: String, _ language: AppLanguage) -> String {
        let zh: [String: String] = [
            "quickShelf": "快速暂存",
            "pinned": "置顶",
            "recent": "智能最近",
            "workingSet": "工作集",
            "workingSetAdd": "加入工作集",
            "workingSetRemove": "移出工作集",
            "workingSetAdded": "已加入工作集",
            "workingSetRemoved": "已移出工作集",
            "workingSetCleared": "工作集已清空",
            "localResults": "本地文件结果",
            "search": "搜索名称或内容…",
            "searchUnified": "搜索目录、文件、文字或网址…",
            "finderQuickPaths": "Finder 快捷目录",
            "finderDefaultPath": "默认目录",
            "openFolder": "打开目录",
            "copyPath": "复制路径",
            "pathCopied": "路径已复制",
            "unifiedFooter": "Finder + 工作集 + Smart Recent",
            "semanticIP": "IP",
            "semanticSSH": "SSH",
            "semanticCommand": "命令",
            "semanticPath": "路径",
            "semanticURL": "URL",
            "add": "添加",
            "settings": "设置",
            "clear": "清空",
            "copied": "已复制",
            "clipboardCaught": "已暂存刚复制的文字",
            "empty": "这里还没有内容",
            "emptyHint": "拖文件或文字到刘海，或复制文字后触碰刘海。",
            "addText": "新建文字",
            "addFile": "添加文件…",
            "addFolder": "添加文件夹…",
            "addURL": "添加网址…",
            "addApp": "添加应用…",
            "addAction": "添加安全操作…",
            "copy": "复制",
            "quickLook": "快速预览",
            "reveal": "在 Finder 中显示",
            "pin": "置顶",
            "unpin": "取消置顶",
            "edit": "编辑",
            "remove": "移除",
            "deleteSelected": "删除所选",
            "copySelected": "复制所选",
            "selected": "已选择",
            "dropTitle": "松开即可放入",
            "dropHint": "文件、文件夹、网址和文字均可直接拖入",
            "dropReference": "引用原文件",
            "dropCopy": "复制到暂存区",
            "name": "名称",
            "content": "内容",
            "cancel": "取消",
            "save": "保存",
            "general": "通用",
            "language": "语言",
            "launchAtLogin": "登录时启动",
            "displayTarget": "显示位置",
            "keepShelfOpen": "常驻展开",
            "keepShelfOpenOn": "常驻展开（不自动隐藏）",
            "keepShelfOpenOff": "取消常驻",
            "allDisplays": "所有显示器",
            "mouseDisplay": "鼠标所在屏幕",
            "primaryDisplay": "主屏幕",
            "currentDisplay": "最近使用屏幕",
            "storage": "暂存",
            "fileDropMode": "文件放置方式",
            "reference": "引用原文件",
            "copyIn": "复制进来",
            "recentCleanup": "Recent 自动清理",
            "never": "永不",
            "oneHour": "1 小时",
            "oneDay": "24 小时",
            "threeDays": "3 天",
            "sevenDays": "7 天",
            "clipboardHint": "按当前 App、语义、最近使用和频率智能排序",
            "openShelf": "打开快速暂存区",
            "newText": "新建文字…",
            "quit": "退出 Ops Notch",
            "safePath": "本地路径",
            "safeURL": "HTTP/HTTPS URL",
            "invalidAction": "安全操作只允许本地绝对路径或 HTTP/HTTPS URL。",
            "dragHandle": "拖动",
            "zoomPreview": "放大预览",
            "previewClose": "关闭",
            "previewFont": "字号",
            "previewFit": "适配窗口",
            "previewZoomIn": "放大",
            "previewZoomOut": "缩小",
            "appTitle": "Ops Notch",
            "settingsTitle": "Ops Notch 设置",
            "hotkeyRow": "呼出快捷键",
            "hotkeyNone": "未设置(点击录制)",
            "hotkeyRecording": "按下组合键,Esc 取消",
            "hotkeyRerecordHint": "点击重新录制,⌫ 清除",
            "hotkeyInvalid": "组合需包含 ⌘/⌃/⌥ 之一",
            "hotkeyConflict": "该组合键已被占用,请换一组",
            "hotkeyHint": "在任意应用中按下快捷键即可呼出 Smart Quick Shelf；Finder、工作集和剪贴板内容在同一面板。",
            "filterAll": "全部",
            "filterFile": "文件",
            "filterText": "文本",
            "filterURL": "URL",
            "filterApp": "应用",
            "noMatch": "没有匹配的条目"
        ]
        let en: [String: String] = [
            "quickShelf": "Quick Shelf",
            "pinned": "Pinned",
            "recent": "Smart Recent",
            "workingSet": "Working Set",
            "workingSetAdd": "Add to Working Set",
            "workingSetRemove": "Remove from Working Set",
            "workingSetAdded": "Added to Working Set",
            "workingSetRemoved": "Removed from Working Set",
            "workingSetCleared": "Working Set cleared",
            "localResults": "Local File Results",
            "search": "Search name or content…",
            "searchUnified": "Search folders, files, text or URLs…",
            "finderQuickPaths": "Finder Quick Folders",
            "finderDefaultPath": "Default Folder",
            "openFolder": "Open Folder",
            "copyPath": "Copy Path",
            "pathCopied": "Path copied",
            "unifiedFooter": "Finder + Working Set + Smart Recent",
            "semanticIP": "IP",
            "semanticSSH": "SSH",
            "semanticCommand": "Command",
            "semanticPath": "Path",
            "semanticURL": "URL",
            "add": "Add",
            "settings": "Settings",
            "clear": "Clear",
            "copied": "Copied",
            "clipboardCaught": "Copied text saved",
            "empty": "Nothing here yet",
            "emptyHint": "Drag files or text to the notch, or copy text and touch the notch.",
            "addText": "New Text",
            "addFile": "Add File…",
            "addFolder": "Add Folder…",
            "addURL": "Add URL…",
            "addApp": "Add Application…",
            "addAction": "Add Safe Action…",
            "copy": "Copy",
            "quickLook": "Quick Look",
            "reveal": "Show in Finder",
            "pin": "Pin",
            "unpin": "Unpin",
            "edit": "Edit",
            "remove": "Remove",
            "deleteSelected": "Delete selected",
            "copySelected": "Copy selected",
            "selected": "Selected",
            "dropTitle": "Release to add",
            "dropHint": "Files, folders, URLs and text are accepted",
            "dropReference": "Reference original",
            "dropCopy": "Copy into Shelf",
            "name": "Name",
            "content": "Content",
            "cancel": "Cancel",
            "save": "Save",
            "general": "General",
            "language": "Language",
            "launchAtLogin": "Launch at login",
            "displayTarget": "Show on",
            "keepShelfOpen": "Keep Shelf Open",
            "keepShelfOpenOn": "Keep open (no auto-hide)",
            "keepShelfOpenOff": "Turn off Keep Open",
            "allDisplays": "All displays",
            "mouseDisplay": "Display under pointer",
            "primaryDisplay": "Primary display",
            "currentDisplay": "Last used display",
            "storage": "Shelf",
            "fileDropMode": "File drop mode",
            "reference": "Reference original",
            "copyIn": "Copy in",
            "recentCleanup": "Recent cleanup",
            "never": "Never",
            "oneHour": "1 hour",
            "oneDay": "24 hours",
            "threeDays": "3 days",
            "sevenDays": "7 days",
            "clipboardHint": "Ranked by current app, semantics, recency and usage",
            "openShelf": "Open Quick Shelf",
            "newText": "New Text…",
            "quit": "Quit Ops Notch",
            "safePath": "Local path",
            "safeURL": "HTTP/HTTPS URL",
            "invalidAction": "Safe Action only supports an absolute local path or HTTP/HTTPS URL.",
            "dragHandle": "Drag",
            "zoomPreview": "Magnify",
            "previewClose": "Close",
            "previewFont": "Font size",
            "previewFit": "Fit to Window",
            "previewZoomIn": "Zoom In",
            "previewZoomOut": "Zoom Out",
            "appTitle": "Ops Notch",
            "settingsTitle": "Ops Notch Settings",
            "hotkeyRow": "Summon Hotkey",
            "hotkeyNone": "Not set (click to record)",
            "hotkeyRecording": "Press keys, Esc to cancel",
            "hotkeyRerecordHint": "Click to re-record, ⌫ to clear",
            "hotkeyInvalid": "Combination must include ⌘/⌃/⌥",
            "hotkeyConflict": "Combination already in use, try another",
            "hotkeyHint": "Press the hotkey in any app to summon Smart Quick Shelf with Finder, Working Set and clipboard content together.",
            "filterAll": "All",
            "filterFile": "Files",
            "filterText": "Text",
            "filterURL": "URLs",
            "filterApp": "Apps",
            "noMatch": "No matching items"
        ]
        return (language == .zhCN ? zh : en)[key] ?? key
    }
}
#endif
